name: CI/CD

on: [push, pull_request]

concurrency: cicd

jobs:
  build-and-test-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: make
      - name: Install gh dispatch
        run: make install
      - name: Acceptance test
        run: make acc-test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure unique version
        run: make check-tag

  build-and-publish-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test-snapshot
    environment:
      name: release
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Create release tag
        run: make tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
