name: Hello

on:
  repository_dispatch:
    types: ["hello"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: say-hello
        run: |
          if [ "${{ github.event.client_payload.force_fail }}" = "true" ]; then
            echo "forced fail"
            exit 1
          fi

          echo "Hello, ${{ github.event.client_payload.name }}!"
