name: Hello

on:
  repository_dispatch:
    types: ["hello"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: say-hello
        run: echo "Hello, ${{ github.event.client_payload.name }}!"
