name: Goodbye

on:
  workflow_dispatch:
    inputs:
      name:
        description: "The name to address"
        type: string
        required: true
      force_fail:
        description: "Deliberately force the run to fail"
        type: boolean
        required: false
        default: false

jobs:
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: say-goodbye
        run: |
          if [ "${{ inputs.force_fail }}" = "true" ]; then
            echo "forced fail"
            exit 1
          fi

          echo "Goodbye, ${{ inputs.name }}!"
